# Koristi se zvanični Docker image za Mosquitto
FROM eclipse-mosquitto:2.0.18

# Kopira custom mosquitto.conf u direktorijum za konfiguraciju Mosquitto-a
COPY mosquitto.conf /mosquitto/config/mosquitto.conf
