version: '3.8'

services:
  mqtt-broker:
    build: ./mqtt-broker
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  sensor-service:
    build: ./sensor-service
    container_name: sensor-service
    depends_on:
      - mqtt-broker
      - mongodb

  analytics-service:
    build: ./analytics-service
    container_name: analytics-service
    depends_on:
      - mqtt-broker

  eventinfo-service:
    build: ./eventinfo-service
    container_name: eventinfo-service
    ports:
      - "3000:3000"
    depends_on:
      - mqtt-broker

volumes:
  mongo-data:
